// Generated by https://quicktype.io


export interface DataKana {
  currentPriceList: CurrentPriceList;
}

export interface CurrentPriceList {
  version:   number;
  createdAt: Date;
  createdBy: CreatedBy;
  products: Products;
}

export interface CreatedBy {
  displayName: string;
}



export interface Products {
  edges:    Edge[];

}

export interface Edge {
  node: Node;
}

export interface Node {
  product: Product;
}

export interface Product {
  id:             string;
  barcode:        string;
  name:           string;
  images:         string[];
  presentation:   string;

  pricePublished: PricePublished;
}



export interface PricePublished {
  priceBase: PriceBase;
}

export interface PriceBase {
  amount: string;
}


