// Generated by https://quicktype.io

export interface Data {
  data: DataKana;
}

export interface DataKana {
  currentPriceList: CurrentPriceList;
}

export interface CurrentPriceList {
  products: Products;
}

export interface Products {
  edges:    Edge[];
  pageInfo: PageInfo;
}

export interface Edge {
  node: Node;
}

export interface Node {
  product: Product;
}

export interface Product {
  id:             string;
  barcode:        string;
  name:           string;
  images:         string[];
  presentation:   string;
  departments:    Department[];
  pricePublished: PricePublished;
}

export interface Department {
  description: string;
}

export interface PricePublished {
  priceBase: PriceBase;
}

export interface PriceBase {
  amount: string;
}

export interface PageInfo {
  hasNextPage:     boolean;
  hasPreviousPage: boolean;
  startCursor:     string;
  endCursor:       string;
}
