// Generated by https://quicktype.io





export interface CurrentPriceList {
  products: Products;
}

export interface Products {
  edges:    Edge[];

}

export interface Edge {
  node: Node;
}

export interface Node {
  product: Product;
}

export interface Product {
  id:             string;
  barcode:        string;
  name:           string;
  images:         string[];
  presentation:   string;
  
  pricePublished: PricePublished;
}



export interface PricePublished {
  priceBase: PriceBase;
}

export interface PriceBase {
  amount: string;
}


